import json

translations = {
  "addAnotherProduct": "إضافة منتج آخر",
  "address": "العنوان *",
  "areaZone": "المنطقة / النطاق",
  "askForBackEntranceParkOnSideStreet": "اسأل عن المدخل الخلفي. أوقف السيارة في الشارع الجانبي.",
  "awaitingApproval": "بانتظار الموافقة",
  "awaitingDelivery": "بانتظار التوصيل",
  "back": "رجوع",
  "businessName": "اسم النشاط التجاري *",
  "customer": "العميل",
  "customerType": "نوع العميل",
  "changePhoto": "تغيير الصورة",
  "collected": "تم التحصيل",
  "collectionProgress": "تقدم التحصيل",
  "collectionsWallet": "التحصيلات والمحفظة",
  "completeLocationVerificationAndPhotoToUnlockTheRemainingFields": "أكمل التحقق من الموقع والصورة لفتح الحقول المتبقية.",
  "completeTheChecklistToStartYourSession": "أكمل القائمة لبدء جلستك",
  "confirmQuantitiesLoaded": "تأكيد الكميات المحملة",
  "createSalesOrder": "إنشاء أمر بيع",
  "customerAdded": "تمت إضافة العميل!",
  "doLinesStops": "خطوط أمر التوزيع / المحطات",
  "downtown": "وسط المدينة",
  "driver": "السائق",
  "due": "مستحق",
  "financialSummary": "الملخص المالي",
  "finance": "المالية",
  "financialCustodyInvoices": "العهدة المالية والفواتير",
  "fullRoute": "المسار الكامل",
  "goodEvening": "مساء الخير 👋",
  "goodEvening2": "مساء الخير،",
  "goodsLoadedOnYourTruck": "البضائع المحملة على شاحنتك",
  "goodsToDeliver": "البضائع المراد توصيلها",
  "handleJuiceCartonsCarefullyFragileColdChainMaintained": "تعامل مع كراتين العصير بعناية - قابلة للكسر. تم الحفاظ على سلسلة التبريد.",
  "invoices": "الفواتير",
  "invoice": "فاتورة",
  "invoiceTotal": "إجمالي الفاتورة",
  "loadingInProgress": "جاري التحميل...",
  "navigate": "تنقل",
  "navigateToTheStopToBegin": "تنقل إلى المحطة للبدء",
  "newOrderDraft": "مسودة طلب جديد",
  "noDetailsAvailable": "لا تتوفر تفاصيل",
  "noStopsCompletedYet": "لم يتم إنجاز أي محطات بعد",
  "orderSummary": "ملخص الطلب",
  "offload": "تفريغ",
  "orderCreated": "تم إنشاء الطلب!",
  "outstanding": "معلق",
  "physicalCustody": "العهدة المادية",
  "products": "المنتجات",
  "paid": "مدفوع",
  "pending": "قيد الانتظار",
  "preRouteChecklist": "قائمة التحقق قبل المسار",
  "resendCode": "إعادة إرسال الرمز",
  "resetPassword": "إعادة تعيين كلمة المرور",
  "salesOrderDetails": "تفاصيل أمر البيع",
  "skusQuantities": "المنتجات والكميات",
  "step1VerifyLocation": "الخطوة 1 — التحقق من الموقع",
  "step2ShopPhoto": "الخطوة 2 — صورة المتجر",
  "saveCustomer": "حفظ العميل",
  "selectProduct": "اختر منتج...",
  "sendResetLink": "إرسال رابط إعادة التعيين",
  "startDaySession": "بدء جلسة اليوم",
  "totalCollected": "إجمالي المحصل",
  "takeAPhotoOfTheShop": "التقط صورة للمتجر",
  "tapToCaptureCurrentLocationPhoto": "انقر لالتقاط صورة للموقع الحالي",
  "tapToSelectACustomer": "انقر لاختيار عميل",
  "total": "المجموع",
  "totalCustody": "إجمالي العهدة",
  "totalInvoice": "إجمالي الفاتورة",
  "totalInvoiced": "إجمالي المفوتر",
  "truckLoad": "حمولة الشاحنة",
  "verification": "التحقق",
  "verificationStepsCompletedYouCanNowFillInTheStoreDetails": "اكتملت خطوات التحقق! يمكنك الآن ملء تفاصيل المتجر.",
  "verifyCustomerLocation": "التحقق من موقع العميل",
  "viewDo": "عرض أمر التوزيع",
  "viewSalesOrderDetails": "عرض تفاصيل أمر البيع",
  "virtualWarehouse": "المستودع الافتراضي",
  "wazza3Distribution": "توزيع وزع",
  "wazza3V10": "وزع · v1.0",
  "warehouseIsLoadingYourTruckConfirmWhenDone": "المستودع يقوم بتحميل شاحنتك. قم بالتأكيد عند الانتهاء.",
  "goodEvening3": "مساء الخير",
  "num0OfRouteCollected": "0% من المسار تم تحصيله",
  "num2Lines116Units": "2 خطوط · 116 وحدة",
  "num4UpcomingStops": "4 محطات قادمة",
  "num5Skus": "5 منتجات"
}

with open('lib/l10n/app_ar.arb', 'r', encoding='utf-8') as f:
    app_ar = json.load(f)

for k, v in translations.items():
    if k in app_ar:
        app_ar[k] = v

with open('lib/l10n/app_ar.arb', 'w', encoding='utf-8') as f:
    json.dump(app_ar, f, indent=2, ensure_ascii=False)
